Repository Dimdim28/to_do_list_frontend, pull requests merged in 2023-02, with the labels that each got.

#9 Added card to edit category
  package-lock.json
  package.json
  src/App.tsx
  src/components/common/Button/Button.module.scss
  src/components/common/Button/Button.tsx
  src/components/common/Checkbox/Checkbox.module.scss
  src/components/common/Checkbox/Checkbox.tsx
  src/components/common/Modal/Modal.module.scss
  src/components/common/Modal/Modal.tsx
  src/components/common/Select/Select.module.scss
  src/components/common/Select/Select.tsx
  src/index.tsx
  src/pages/Category/Category.module.scss
  src/pages/Category/Category.tsx
  src/pages/CategoryForm/CategoryForm.module.scss
  src/pages/CategoryForm/CategoryForm.tsx
  src/pages/Home/Filters/Category/Category.module.scss
  src/pages/Home/Filters/Category/Category.tsx
  src/pages/Home/Filters/Filters.module.scss
  src/pages/Home/Filters/Filters.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/Tasks/Tasks.module.scss
  src/redux/slices/auth/selectors.ts
  src/redux/slices/category/category.ts
  src/redux/slices/category/selectors.ts
  src/redux/slices/category/thunk.ts
  src/redux/slices/category/types.ts
  src/redux/slices/home/home.ts
  src/redux/slices/home/selectors.ts
  src/redux/slices/home/thunk.ts
  src/redux/slices/home/types.ts
  src/redux/store.ts
Labels: bug

#11 Added ability to delete category
  src/api/deleteCategory.ts
  src/components/common/Input/Input.module.scss
  src/components/common/Input/Input.tsx
  src/pages/Home/FiltersBar/Category/Category.tsx
  src/pages/Home/FiltersBar/CategoryDeleting/CategoryDeleting.module.scss
  src/pages/Home/FiltersBar/CategoryDeleting/CategoryDeleting.tsx
  src/pages/Home/FiltersBar/CategoryForm/CategoryForm.module.scss
  src/pages/Home/FiltersBar/CategoryForm/CategoryForm.tsx
  src/pages/Home/FiltersBar/FiltersBar.tsx
  src/pages/Profile/Profile.module.scss
  src/pages/Profile/Profile.tsx
  src/redux/slices/home/home.ts
Labels: enhancement

#18 Added ability to hide or show password
  src/components/common/Input/Input.module.scss
  src/components/common/Input/Input.tsx
  src/index.tsx
  src/pages/Login/Login.module.scss
  src/pages/Register/Register.module.scss
  src/pages/Register/Register.tsx
Labels: enhancement

#20 Added ability to change avatar
  package-lock.json
  package.json
  src/components/common/Modal/Modal.module.scss
  src/hoc/withHomeRedirect.tsx
  src/hoc/withLoginRedirect.tsx
  src/index.tsx
  src/pages/Profile/Profile.module.scss
  src/pages/Profile/Profile.tsx
  src/redux/slices/profile/profile.ts
  src/redux/slices/profile/selectors.ts
  src/redux/slices/profile/thunk.ts
  src/redux/slices/profile/types.ts
Labels: enhancement

#21 Added ability to delete account
  src/pages/Profile/ChangePass/ChangePass.module.scss
  src/pages/Profile/ChangePass/ChangePass.tsx
  src/pages/Profile/DeleteProfile/DeleteProfile.module.scss
  src/pages/Profile/DeleteProfile/DeleteProfile.tsx
  src/pages/Profile/Profile.module.scss
  src/pages/Profile/Profile.tsx
  src/redux/slices/profile/profile.ts
  src/redux/slices/profile/thunk.ts
  src/redux/slices/profile/types.ts
Labels: enhancement

#23 Added ability to change password
  src/pages/Profile/ChangePass/ChangePass.tsx
  src/pages/Profile/Profile.module.scss
  src/pages/Profile/Profile.tsx
  src/redux/slices/profile/profile.ts
  src/redux/slices/profile/thunk.ts
  src/redux/slices/profile/types.ts
Labels: enhancement

#25 Added ability to change username
  src/pages/Profile/Profile.module.scss
  src/pages/Profile/Profile.tsx
  src/redux/slices/auth/auth.ts
  src/redux/slices/home/home.ts
  src/redux/slices/profile/profile.ts
  src/redux/slices/profile/thunk.ts
  src/redux/slices/profile/types.ts
Labels: enhancement

#27 Develop
  src/pages/Home/Tasks/TaskDeleting/TaskDeleting.module.scss
  src/pages/Home/Tasks/TaskDeleting/TaskDeleting.tsx
  src/pages/Home/Tasks/Tasks.tsx
Labels: help wanted
