Repository Dimdim28/to_do_list_frontend, pull requests merged in 2023-11, with the labels that each got.

#103 Add more tests to header
  src/components/Header/Header.test.tsx
  src/components/Header/Header.tsx
  src/mocs/localstorage.ts
Labels: tests

#104 refactor: Header component
  src/components/Header/Header.tsx
Labels: refactoring

#105 refactor: combined headers into one component
  src/App.tsx
  src/components/Header/Header.test.tsx
  src/components/Header/Header.tsx
  src/components/SecondHeader/SecondHeader.module.scss
  src/components/SecondHeader/SecondHeader.test.tsx
  src/components/SecondHeader/SecondHeader.tsx
  src/layouts/AuthLayout.test.jsx
  src/layouts/AuthLayout.tsx
  src/layouts/FAQLayout.tsx
  src/layouts/HomeLayout.tsx
  src/layouts/PageLayout.tsx
Labels: refactoring

#106 test: added more tests to links rendering, removed dumb data route
  src/App.tsx
  src/components/Header/Header.test.tsx
  src/pages/Task/Task.module.scss
  src/pages/Task/Task.tsx
  src/routes.ts
Labels: tests

#108 refactor: added links list rendering in FAQFooter
  src/App.tsx
  src/components/FAQFooter/FAQFooter.test.tsx
  src/components/FAQFooter/FAQFooter.tsx
  src/components/Footer/Footer.module.scss
  src/components/Footer/Footer.test.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.module.scss
  src/layouts/AuthLayout.test.jsx
  src/layouts/AuthLayout.tsx
  src/layouts/FAQLayout.tsx
  src/layouts/HomeLayout.tsx
  src/layouts/PageLayout.test.jsx
  src/layouts/PageLayout.tsx
Labels: refactoring

#109 refactor: rename all FAQFooter entries to Footer
  src/components/Footer/Footer.module.scss
  src/components/Footer/Footer.test.tsx
  src/components/Footer/Footer.tsx
  src/layouts/AuthLayout.test.jsx
  src/layouts/AuthLayout.tsx
  src/layouts/FAQLayout.tsx
  src/layouts/HomeLayout.test.jsx
  src/layouts/HomeLayout.tsx
  src/layouts/PageLayout.test.jsx
  src/layouts/PageLayout.tsx
Labels: refactoring

#110 test: added tests for lists rendering
  src/components/Footer/Footer.test.tsx
  src/components/Header/Header.test.tsx
  src/mocs/links.ts
Labels: tests

#111 Headers and Footers refactoring and tests covering
  src/App.tsx
  src/components/FAQFooter/FAQFooter.module.scss
  src/components/FAQFooter/FAQFooter.test.tsx
  src/components/FAQFooter/FAQFooter.tsx
  src/components/Footer/Footer.module.scss
  src/components/Footer/Footer.test.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.module.scss
  src/components/Header/Header.test.tsx
  src/components/Header/Header.tsx
  src/components/SecondHeader/SecondHeader.module.scss
  src/components/SecondHeader/SecondHeader.test.tsx
  src/components/SecondHeader/SecondHeader.tsx
  src/layouts/AuthLayout.test.jsx
  src/layouts/AuthLayout.tsx
  src/layouts/FAQLayout.tsx
  src/layouts/HomeLayout.test.jsx
  src/layouts/HomeLayout.tsx
  src/layouts/PageLayout.tsx
  src/mocs/links.ts
  src/mocs/localstorage.ts
  src/pages/Task/Task.module.scss
  src/pages/Task/Task.tsx
  src/routes.ts
  src/types.ts
Labels: refactoring, tests

#113 Develop
  src/components/common/Checkbox/Checkbox.test.tsx
  src/components/common/Checkbox/Checkbox.tsx
  src/pages/Home/Tasks/TaskCard/TaskCard.tsx
  src/pages/Home/Tasks/TaskEditing/TaskForm.tsx
Labels: refactoring, tests

#114 tests: profile refactored and tested
  src/pages/Profile/ChangePass/ChangePass.module.scss
  src/pages/Profile/DeleteProfile/DeleteProfile.tsx
  src/pages/Profile/Exit/Exit.tsx
  src/pages/Profile/Profile.module.scss
  src/pages/Profile/Profile.tsx
  src/pages/Profile/ProfileCard/Avatar/Avatar.module.scss
  src/pages/Profile/ProfileCard/Avatar/Avatar.test.tsx
  src/pages/Profile/ProfileCard/Avatar/Avatar.tsx
  src/pages/Profile/ProfileCard/Buttons/Buttons.module.scss
  src/pages/Profile/ProfileCard/Buttons/Buttons.test.tsx
  src/pages/Profile/ProfileCard/Buttons/Buttons.tsx
  src/pages/Profile/ProfileCard/DeleteProfile/DeleteProfile.module.scss
  src/pages/Profile/ProfileCard/DeleteProfile/DeleteProfile.test.tsx
  src/pages/Profile/ProfileCard/DeleteProfile/DeleteProfile.tsx
  src/pages/Profile/ProfileCard/Exit/Exit.module.scss
  src/pages/Profile/ProfileCard/Exit/Exit.test.tsx
  src/pages/Profile/ProfileCard/Exit/Exit.tsx
  src/pages/Profile/ProfileCard/Name/Name.module.scss
  src/pages/Profile/ProfileCard/Name/Name.test.tsx
  src/pages/Profile/ProfileCard/Name/Name.tsx
  src/pages/Profile/ProfileCard/ProfileCard.module.scss
  src/pages/Profile/ProfileCard/ProfileCard.test.tsx
  src/pages/Profile/ProfileCard/ProfileCard.tsx
  src/pages/Profile/ProfileCard/ProfileData/ProfileData.module.scss
  src/pages/Profile/ProfileCard/ProfileData/ProfileData.test.tsx
  src/pages/Profile/ProfileCard/ProfileData/ProfileData.tsx
Labels: refactoring, tests

#115 Vite migration
  .eslintrc.cjs
  .prettierrc
  __mocks__/filemock.js
  __mocks__/stylemock.js
  index.html
  package-lock.json
  package.json
  public/index.html
  src/axios.ts
  src/components/Footer/Footer.tsx
  src/hoc/withLoginRedirect.test.ts
  src/hoc/withLoginRedirect.tsx
  src/pages/FAQ/FAQ.tsx
  src/pages/Home/FiltersBar/Categories/Category/Category.test.tsx
  src/pages/Home/Tasks/TaskCard/TaskCard.tsx
  src/pages/Home/Tasks/TaskEditing/TaskForm.tsx
  src/react-app-env.d.ts
  src/vite-env.d.ts
  tsconfig.json
  vite.config.js
Labels: enhancement

#116 Vite migration
  .eslintrc.cjs
  .prettierrc
  __mocks__/filemock.js
  __mocks__/stylemock.js
  index.html
  package-lock.json
  package.json
  public/index.html
  src/axios.ts
  src/components/Footer/Footer.tsx
  src/hoc/withLoginRedirect.test.ts
  src/hoc/withLoginRedirect.tsx
  src/pages/FAQ/FAQ.tsx
  src/pages/Home/FiltersBar/Categories/Category/Category.test.tsx
  src/pages/Home/Tasks/TaskCard/TaskCard.tsx
  src/pages/Home/Tasks/TaskEditing/TaskForm.tsx
  src/react-app-env.d.ts
  src/vite-env.d.ts
  tsconfig.json
  vite.config.js
Labels: enhancement
